engines:
  eslint:
    enabled: true
  duplication:
      enabled: true
      config:
        languages:
        - javascript: true

ratings:
  paths:
  - src/**

exclude_paths:
- docs/**
- "**/*.spec.js"