# https://circleci.com/docs/2.0/workflows/

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9-stretch-browsers
      - image: circleci/python:3.7-rc-stretch-browsers
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "package.json" }}
      - run: yarn install
      - run: yarn build
      - run: yarn generate-sitemap
      - save_cache: 
          key: node_modules-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/project
          paths:
            - dist
      - store_artifacts:
          path: dist

  test:
    docker:
      - image: circleci/node:8.9-stretch-browsers
      - image: circleci/python:3.7-rc-stretch-browsers
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "package.json" }}
      - run: yarn install
      - run: yarn test
      - run: yarn coverage

  deploy:
    docker:
      - image: circleci/node:8.9-stretch-browsers
      - image: circleci/python:3.7-rc-stretch-browsers
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "package.json" }}
      - attach_workspace:
          at: ~/project
      - run: yarn install
      - run: yarn deploy
      
workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - build
            - test
