# https://circleci.com/docs/2.0/workflows/

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9-stretch-browsers
      - image: circleci/python:3.7-rc-stretch-browsers
    steps:
      - checkout
      - run: lsb_release -a
      - run: yarn install
      - run: yarn build
    persist_to_workspace:
      root: ~/project
      paths:
        - dist

  test:
    docker:
      - image: circleci/node:8.9-stretch-browsers
      - image: circleci/python:3.7-rc-stretch-browsers
    steps:
      - checkout
      - run: yarn install
      - run: yarn test

  coverage:
    docker:
      - image: circleci/node:8.9-stretch-browsers
      - image: circleci/python:3.7-rc-stretch-browsers
    steps:
      - checkout
      - run: yarn install
      - run: yarn coverage

  deploy:
    docker:
      - image: circleci/node:8.9-stretch-browsers
      - image: circleci/python:3.7-rc-stretch-browsers
    attach_workspace:
      at: ~/project
    steps:
      - checkout
      - run: yarn install
      - run: yarn deploy

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test
      - coverage
      - deploy:
          requires:
            - build
            - test
            # - coverage






# machine:
#   # python:
#   #   version: 2.7.10
#   node:
#     version: 8.9.4
#   environment:
#     PATH: "${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin"

# dependencies:
#   override:
#     - yarn
#   cache_directories:
#     - ~/.cache/yarn
#   # pre:
#   #   - pip install boto
#   #   - pip install ansible

# test:
#   override:
#     - yarn build
#     - yarn lint
#     - yarn test

# deployment:
#   dev:
#     branch: master
#     commands:
#       - yarn deploy
