service: react-redux-complete-example

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-southeast-2

plugins:
  - serverless-finch

custom:
  client:
    bucketName: reactexample.dev.johngeddes.tech
    distributionFolder: dist # (Optional) The location of your website. This defaults to client/dist
    indexDocument: index.html # (Optional) The name of your index document inside your distributionFolder. Defaults to index.html
    errorDocument: error.html # (Optional) The name of your error document inside your distributionFolder. Defaults to error.html
